tango_with_django_project/rango/urls.py
from django.urls import path
from rango import views

app_name = "rango"

urlpatterns = [
    path("", views.index, name="index"),
    path("about/", views.about, name="about"),
    path(
        "category/<slug:category_name_slug>/", views.show_category, name="show_category"
    ),
    path("add_category/", views.add_category, name="add_category"),
    path(
        "category/<slug:category_name_slug>/add_page/", views.add_page, name="add_page"
    ),
    # category/<category_name_slug>/add_page/
]

tango_with_django_project/tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

from django.conf import settings
from django.conf.urls.static import static

from rango import views

urlpatterns = [
    path('', views.index, name='index'),
    path('rango/', include('rango.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tango_with_django_project/rango/models.py
from django.db import models
from django.template.defaultfilters import slugify


class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)
    name_limit = models.IntegerField(default=128)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name


class Page(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)
    # title_limit = models.IntegerField(_("128"))
    title_limit = models.IntegerField(default=128)
    url_limit = models.IntegerField(default=200)

    def __str__(self):
        return self.title

tango_with_django_project/rango/forms.py
from django import forms
from rango.models import Page, Category


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text="Please enter a category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ("name",)


class PageForm(forms.ModelForm):
    title = forms.CharField(
        max_length=128, help_text="Please enter the title of the page."
    )
    url = forms.URLField(max_length=200, help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get("url")
        if url and not url.startswith("http://"):
            url = "http://" + url
            cleaned_data["url"] = url
            return cleaned_data

    class Meta:
        model = Page
        exclude = ("category",)

tango_with_django_project/rango/views.py
from django.shortcuts import render
from django.http import HttpResponse
from rango.models import Category, Page
from rango.forms import CategoryForm, PageForm


def index(request):
    category_list = Category.objects.order_by("-likes")[:5]
    page_list = Page.objects.order_by("-views")[:5]
    context_dict = {}
    context_dict["boldmessage"] = "Crunchy, creamy, cookie, candy, cupcake!"
    context_dict["categories"] = category_list
    context_dict["pages"] = page_list
    return render(request, "rango/index.html", context=context_dict)
    # return HttpResponse("Rango says hey there partner! <br/> <a href='/rango/about/'>About Page</a>")


def about(request):
    context_dict = {"msg": "Winner! Winner! Chicken dinner!!"}
    return render(request, "rango/about.html", context=context_dict)
    # return HttpResponse("Rango says here is the about page. <br/> <a href='/rango/'>Home Page (Index)</a>")


def show_category(request, category_name_slug):
    context_dict = {}
    try:
        category = Category.objects.get(slug=category_name_slug)
        pages = Page.objects.filter(category=category)
        context_dict["pages"] = pages
        context_dict["category"] = category
    except Category.DoesNotExist:
        context_dict["pages"] = None
        context_dict["category"] = None
    return render(request, "rango/category.html", context=context_dict)


def add_category(request):
    form = CategoryForm()
    if request.method == "POST":
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print(form.errors)
    return render(request, "rango/add_category.html", {"form": form})


def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None

    form = PageForm()
    if request.method == "POST":
        form = PageForm(request.POST)
        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()
                return show_category(request, category_name_slug)
        else:
            print(form.errors)

    context_dict = {"form": form, "category": category}
    return render(request, "rango/add_page.html", context_dict)

tango_with_django_project/templates/rango/about.html
{% extends "rango/base.html" %}
{% load staticfiles %}


{% block title_block %}
About Rango
{% endblock %}

{% block body_block %}
<h1>Rango says...</h1>
<div>
    ...here is the about page.
</div>
<img src='{{ MEDIA_URL }}cat.png' alt='cat' />
<br>
<h4>This beautiful page was laboriously put together by the very attractive Ian Pollack.</h4>
<img src='{% static "images/rango.jpg" %}'>
{% endblock %}

tango_with_django_project/templates/rango/add_category.html
{% extends "rango/base.html" %}
{% load staticfiles %}

{% block title_block %}
Add a Category
{% endblock %}

{% block body_block %}
<h1>Add a Category</h1>
<div>
    <form id="category_form" method="post" action="{% url 'add_category'%}">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
        {{ hidden }}
        {% endfor %}
        {% for field in form.visible_fields %}
        {{ field.errors }}
        {{ field.help_text }}
        {{ field }}
        {% endfor %}
        <input type="submit" name="submit" value="Create Category" />
    </form>
</div>
{% endblock %}

tango_with_django_project/templates/rango/add_page.html
{% extends "rango/base.html" %}
{% load staticfiles %}

{% block title_block %}
Rango
{% endblock %}

{% block body_block %}
<h1>Add a {{ category.name }} Page</h1>
<div>
    <form id="page_form" method="post" action="{% url 'add_page' category.slug %}">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
        {{ hidden }}
        {% endfor %}
        {% for field in form.visible_fields %}
        {{ field.errors }}
        {{ field.help_text }}
        {{ field }}
        {% endfor %}
        <input type="submit" name="submit" value="Create Page" />
    </form>
</div>
{% endblock %}

tango_with_django_project/templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}

<html>
    <head lang="en">
        <meta charset="UTF-8"/>
        <title>
            Rango - 
            {% block title_block %}
                - How to Tango with Django!
            {% endblock %}
        </title>
        <link rel='stylesheet' href='{% static "css/base.css" %}' />
        <script src='{% static "js/jquery.js" %}'></script>
    </head>
    <body>
        <div>
            {% block sidebar_block %}
                {% get_category_list category %}
            {% endblock %}
        </div>
        <div>
            {% block body_block %}
                This is block_body's default content.
            {% endblock %}
        </div>
        <hr />
        <div>
            <ul>
                <li><a href="{% url 'rango:add_category' %}">Add New Category</a></li>
                <li><a href="{% url 'rango:about' %}">About</a></li>
                <li><a href="{% url 'rango:index' %}">Index</a></li>
            </ul>
        </div>
    </body>
</html>

tango_with_django_project/templates/rango/category.html
{% extends "rango/base.html" %}
{% load staticfiles %}

{% block title_block %}
    {{ category.name }}
{% endblock %}

{% block body_block %}
    {% if category %}
        <h1>{{ category.name }}</h1>
        {% if pages %}
            <ul>
                {% for page in pages %}
                    <li><a href="{{ page.url }}">{{ page.title }}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            <strong>No pages currently in category.</strong>
        {% endif %}
        <a href="{% url 'rango:add_page' category.slug %}">Add a Page</a><br>
    {% else %}
        The specific category does not exist!
    {% endif %}
{% endblock %}

tango_with_django_project/templates/rango/cats.html
<ul>
    {% if cats %}
        {% for c in cats %}
            {% if c == act_cat %}
                <li><strong><a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a></strong></li>
            {% else %}
                <li><a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a></li>
            {% endif %}
        {% endfor %}
    {% else %}
        <li><strong>There are no categories present.</strong></li>
    {% endif %}
</ul>

tango_with_django_project/templates/rango/index.html
{% extends "rango/base.html" %}
{% load staticfiles %}

{% block title_block %}
    Rango
{% endblock %}

{% block body_block %}
    <h1>Rango says...</h1>
    <div>
        ...hey there partner! <br>
        <strong>{{ boldmessage }}</strong><br>
    </div>

    <div>
        {% if categories %}
            <h1>Most Liked Categories</h1>
            <ul>
                {% for category in categories %}
                    <li><a href="{% url 'rango:show_category' category.slug %}">{{ category.name }}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            <strong>There are no categories present.</strong>
        {% endif %}
        {% if pages %}
            <h1>Mosted Viewed Pages</h1>
            <ul>
                {% for page in pages %}
                    <li>{{ page.title }}</li>
                {% endfor %}
            </ul>
        {% else %}
            <strong>There are no pages present.</strong>
        {% endif %}
    </div>

    <div>
        <img src=' {% static "images/rango.jpg" %}' alt="Rango Hero Picture" />
        <img src='{{ MEDIA_URL }}cat.png' alt='cat' />
    </div>
{% endblock %}